music/urls.py
from . import views
from django.conf.urls import url
from django.conf import settings
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'(?P<album_id>[0-9]+)/updatealbum',views.updatealbum,name='updatealbum'),
    url(r'^register/$',views.register,name='register'),
    url(r'^login_user/$',views.login_user,name='login_user'),
    url(r'^(?P<album_id>[0-9]+)/$',views.detail,name='details'),
    url(r'^addalbum$',views.addalbum,name='addalbum'),
    url(r'(?P<album_id>[0-9]+)/album/addsong',views.addsong,name='addsong'),
    url(r'(?P<album_id>[0-9]+)/delete/$', views.deletealbum,name='deletealbum'),
    url(r'(?P<album_id>[0-9]+)/song/(?P<song_id>[0-9]+)/delete',views.deletesong,name='deletesong'),
    url(r'^allsongs$',views.allsongs,name='allsongs'),
    url(r'^profile$',views.profile,name='profile'),
    url(r'^logout$',views.logoutuser,name='logoutuser'),
    url(r'^glanceall$',views.glanceall,name='glanceall'),
    url(r'^fetchxml_foralbums$',views.getxml_foralbums,name='getxml_foralbums'),
    url(r'(?P<album_id>[0-9]+)/fetchxml_forsongs',views.getxml_forsongs,name="getxml_forsongs"),
    url(r'^fetchxml_forallsongs$',views.getxml_forallsongs,name="getxml_forallsongs"),
    url(r'^getjson$',views.getjson,name="getjson"),
    url(r'^testangular$',views.test_angular,name="test_angular"),

]

website/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls',namespace="music")),
    url(r'^', include('music.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
class Album(models.Model):
    user = models.ForeignKey(User,default=1)
    artist = models.CharField(max_length=100)
    album_title = models.CharField(max_length=100)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()
    def get_absolute_url(self):
        return reverse('music/detail.html', kwargs={'pk':self.pk })
    def __str__(self):
        return self.album_title + '-' + self.artist

class Song(models.Model):
    album = models.ForeignKey(Album,on_delete=models.CASCADE)
    audio_file = models.FileField(default='')
    song_title = models.CharField(max_length=200)
    def __str__(self):
        return self.song_title


music/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Album,Song


class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ['artist', 'album_title', 'genre', 'album_logo']


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ['audio_file','song_title']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model = User
        fields = ['username','email','password']

music/views.py

from .models import Album,Song
from django.contrib.auth import authenticate,login
from django.shortcuts import render,redirect,get_object_or_404,render_to_response
from .forms import UserForm,AlbumForm,SongForm
from django.views.generic import View
from django.db.models import Q
from django.core import serializers
from django.http import HttpResponse
from django.contrib.auth import logout
from django.http import JsonResponse

def addalbum(request):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        form = AlbumForm(request.POST or None , request.FILES or None)
        if form.is_valid():
            album = form.save(commit=False)
            album.user = request.user
            album.album_logo = request.FILES['album_logo']
            album.save()
            return render(request,'music/detail.html',{'album':album})
        else:
            return render(request,'music/addalbum.html',{'form':form})


def updatealbum(request, album_id):
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        album = get_object_or_404(Album, pk=album_id)
        form = AlbumForm(request.POST, request.FILES)
        if form.is_valid():
            newobj = form.save(commit=False)
            newobj.album_logo = request.FILES['album_logo']
            album.artist = newobj.artist
            album.album_title = newobj.album_title
            album.genre = newobj.genre
            album.album_logo = request.FILES['album_logo']
            album.save()
            return render(request, 'music/detail.html', {'album': album})
        else:
            return render(request, 'music/updatealbum.html', {'form': form,'album':album})

def index(request):

    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        albums = Album.objects.filter(user=request.user)
        return render(request, 'music/index.html', {'albums': albums})

def detail(request,album_id):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        album = get_object_or_404(Album,pk=album_id)
        return render(request,'music/detail.html',{'album':album})

def deletealbum(request,album_id):
    album = get_object_or_404(Album,pk=album_id)
    album.delete()
    albums = Album.objects.filter(user=request.user)
    return render(request,'music/index.html',{'albums':albums})

def deletesong(request,album_id,song_id):
    album = get_object_or_404(Album,pk=album_id)
    song = Song.objects.get(pk=song_id)
    song.delete()
    return render(request,'music/detail.html',{'album':album})

def addsong(request,album_id):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        album = get_object_or_404(Album,pk=album_id)
        if not request.user.is_authenticated():
            return render(request,'music/login.html')
        else:
            form = SongForm(request.POST or None,request.FILES or None)
            if form.is_valid():
                song = form.save(commit=False)
                song.album = album
                song.audio_file = request.FILES['audio_file']
                song.save()
                return render(request,'music/detail.html',{'album':album})
            else:
                return render(request,'music/addsong.html',{'form':form})


def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                albums = Album.objects.filter(user=request.user)
                return render(request, 'music/index.html', {'albums': albums})
    context = {
        "form": form,
    }
    return render(request, 'music/registration_form.html', context)



def allsongs(request):
    all_albums = Album.objects.filter(user=request.user)
    return render(request,'music/allsongs.html',{'all_albums':all_albums})
def profile(request):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        return render(request,'music/profile.html')

def logoutuser(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'music/login.html', context)

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username,password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                albums = Album.objects.filter(user=request.user)
                return render(request,'music/index.html',{'albums':albums})
            else:
                return render(request,'music/login.html',{'error_message':'Your Accont has been disabled'})
        else:
            return render(request,'music/login.html',{'error_message':'You have entered either a wrong username and password. Login Again'})
    else:
        return render(request,'music/login.html',{'error_message':'Hello' })


def glanceall(request):
    if not request.user.is_authenticated():
        return render(request,'music/login.html')
    else:
        albums = Album.objects.filter(user=request.user)
        return render(request,'music/At_a_glance.html',{"albums":albums})


def getxml_foralbums(request):
    albums = Album.objects.filter(user=request.user)
    queryset = serializers.serialize('xml',albums)
    return HttpResponse(queryset,content_type="application/xml")

def getxml_forsongs(request,album_id):
    album_this = get_object_or_404(Album,pk=album_id)
    song = Song.objects.filter(album = album_this)
    queryset = serializers.serialize('xml',song)
    return HttpResponse(queryset,content_type="application/xml")

def getxml_forallsongs(request):
    albums = Album.objects.filter(user=request.user)
    songs = Song.objects.filter(album__in=albums)
    queryset = serializers.serialize('xml',songs)
    return HttpResponse(queryset,content_type="application/xml")
def getjson(request):
    albums = Album.objects.filter(user=request.user)
    queryset = serializers.serialize('json',albums)
    return HttpResponse(queryset,content_type="application/json")
def test_angular(request):
    return render(request,'music/test_angular.html')

music/templates/music/At_a_glance.html
{% extends 'music/base.html' %}
{% load staticfiles %}
{% block body %}
<script src="{% static 'music/dynamic_songs.js' %}" type="text/javascript"></script>

<div class="row">
    <div class="col-sm-6">
    <div class="col-sm-offset-1">
        {% for album in albums %}
            <a href="{% url 'music:details' album.pk %}">
            <img src="{{ album.album_logo.url }}" width="150" height="150" onmouseout="display(-1)" onmouseover="display({{ album.pk }})">
            </a>
            <span class="badge"><h4>{{album.album_title}}</h4><br><br>By: <h5>{{ album.artist }}</h5></span>
            <br><br><br>
        {% endfor %}
    </div>
    </div>
    <div class="col-sm-6">
        <h3><p id="song">Move the mouse over to Album image</h3></p>
    </div>

{% endblock %}

music/templates/music/addalbum.html
{% extends 'music/base.html' %}
{% block title %}Add a New Album{% endblock %}
{% block addalbums %}Active{% endblock %}
{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Album</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>What is ScrollAlbum?</h3>
                    <p>Scrollalbum is an app that allows you to upload and store all of your music on the cloud.</p>
                    <h3>How do I add music?</h3>
                    <p>First, create a new album by filling out the form on this page. Once an album is created you will be able to add/upload songs.</p>
                    <h3>What are some Album logo best practices?</h3>
                    <ul>
                        <li>Have a resolution of 512x512</li>
                        <li>Use common image formats such as .JPG, .GIF, or .PNG</li>
                        <li>Remain under the 2MB limit.</li>
                        <li>Square images look best</li>
                    </ul>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

music/templates/music/addsong.html
{% extends 'music/base.html' %}
{% block title %}Add a new song{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Song</h3>
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/allsongs.html
{% extends 'music/base.html' %}
{% block title %} All Songs {% endblock %}
{% block music %}Active{% endblock %}
{% block body %}

<div class="col-sm-12">
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>SongName</th>
                        <th>Album Name</th>
                        <th>Audio</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for album in all_albums %}
                {% for song in album.song_set.all %}
                    <tr>
                        <td>{{song.song_title}}</td>
                         <td>
                            {{album.album_title}}
                        </td>
                        <td>
                            <a href="{{song.audio_file.url}}"><span class="badge">Play</span></a>
                        </td>
                        <td>
                            <a href="{% url 'music:deletesong' album.id song.id %}">
                                <button><span class="glyphicon glyphicon-trash"></span></button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

music/templates/music/angular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>angular</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
</head>
<body>
<div ng-app="myapp" ng-controller="myctrl">
    <ul>
        <li ng-repeat="x in names">
            {{ x.name | json }}
        </li>
    </ul>
</div>
<script>
    var app = angular.module('myapp',[]);
    app.controller( 'myctrl', function($scope) {
        $scope.names = [
            {name:'Myanka',country:'India'},
            {name:'Ajax',country:"USA"}
        ];
    } );
</script>
</body>
</html>

music/templates/music/base.html
{% load staticfiles %}
<script src="{% static 'music/dynamic_songs.js' %}"></script>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
       <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li><a class='navbar-brand' href="{% url 'music:index' %}">ScrollAlbum</a></li>
                <li class="{% block albums %}{% endblock %}">
                    <a href="{% url 'music:index' %}">
                        <h6><span class="glyphicon glyphicon-cd" aria-hidden="True"></span>&nbsp;
                         Albums</h6>
                    </a>
                </li>
                <li class="{% block music %}{% endblock %}">
                    <a href="{% url 'music:allsongs' %}">
                        <h6><span class="glyphicon glyphicon-music" aria-hidden="True"></span>&nbsp;
                        Music</h6>
                    </a>
                </li>
            </ul>

                    <form method="GET" class="navbar-form navbar-left" autocomplete="off">

                        <input type="text"  onfocus="getsearch_results()" onkeyup="getsearch_results()" id="search" placeholder="Search an album...">
                         <div id="searched">

                         </div>
                    </form>
            <form method="GET" class="navbar-form navbar-left" autocomplete="off">

                <input type="text" onfocus="get_song_search_results()" onkeyup="get_song_search_results()" id="search_song" placeholder="Search a song...">
                <div id="searched_song">

                </div>
            </form>


                <ul class="nav navbar-nav">
                    <a href="{% url 'music:glanceall' %}">

                    </a>
                </ul>


            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'music:glanceall' %}"><h6>
                        <span class="glyphicon glyphicon-eye-open">&nbsp;SmartView</span>
                    </h6></a>
                </li>
            <li class="{% block profile%}{% endblock %}">
                <a href="{% url 'music:profile' %}">
                    <h6><span class="glyphicon glyphicon-user"></span>&nbsp;
                        Your Profile </h6>
                </a>
            </li>
            <li class="{% block addalbums %}{% endblock %}">
                <a href="{% url 'music:addalbum' %}">
                    <h6><span class="glyphicon glyphicon-plus"></span>&nbsp;
                        Add Album</h6>
                </a>
            </li>
            <li class="">
                <a href="{% url 'music:logoutuser' %}">
                    <h6><span class="glyphicon glyphicon-off"></span>&nbsp;
                        Logout</h6>
                </a>
            </li>

        </ul>
        </div>
    </div>
</nav>

<!DOCTYPE html>
<html lang="en">
<head>
    <a href="http://www.google.com">go to google</a>
    <meta charset="UTF-8">
    {% block script %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

{% block body %}
{% endblock %}

</body>
</html>

music/templates/music/baselogin.html
{% load staticfiles %}

    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css'%}">

<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'music:index' %}">DJANGO</a>
        </div>
        <div class="collapse navbar-collapse" id="topNavBar">
            <ul class="nav navbar-nav">
                <li class="{% block register_active %}{% endblock %}"><a href="{% url 'music:register' %}">Register</a></li>
                <li class="{% block login_active %}{% endblock %}"><a href="{% url 'music:login_user' %}">Log In</a></li>
            </ul>
        </div>
    </div>
</nav>
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
{% block body %}
{% endblock %}
</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %} {{album.album_title}} - {{album.artist}}{% endblock %}
{% block body %}
<div class="row">
<div class="col-sm-6">
<div class="col-sm-offset-1">
<img src="{{album.album_logo.url}}" height="350" width="450"><br><br>
    <span class="badge"><h5>Genre : {{album.genre}}</h5></span><br><br>
    <span class="badge"><h5>Artist : {{album.artist}}</h5></span><br><br>
    <span class="badge"><h5>Album Name : {{album.album_title}}</h5></span><br><br>
</div>
</div>
<div class="col-sm-6">
    <a href="{% url 'music:addsong' album.id  %}"><button type="button" class="btn btn-success">ADD SONG</button></a><br><br>
<div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>SongName</th>
                        <th>Audio</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for song in album.song_set.all %}
                    <tr>
                        <td>{{song.song_title}}</td>
                        <td>
                            <a href="{{song.audio_file.url}}"><span class="badge">Play</span></a>
                        </td>
                        <td>
                            <a href="{% url 'music:deletesong' album.id song.id %}">
                                <button><span class="glyphicon glyphicon-trash"></span></button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

music/templates/music/index.html
{% extends 'music/base.html' %}
{% block title %}Albums details{% endblock %}
{% block albums %}Active{% endblock %}
{% block body %}
<div class="container">
    <div class="jumbotron">
        <h2 align="center">{{user.username}}'s <small>Albums</small></h2>
    </div>
</div>
<div class="albums-container container-fluid">
<div class="row">
{% for album in albums %}
    <div class="col-sm-4" >
        <div class="thumbnail">
        <a href="/music/{{album.pk}}">
            <img src="{{album.album_logo.url}}" height="350" width="450">
            <div class="caption">
                <h4 align="center">{{album.artist}}</h4>
                <h3 align="center">{{album.album_title}}</h3>
                <h3 align="center">
                <a href="{% url 'music:updatealbum' album.id %}"><button class="btn btn-success">Update</button></a>
                <form action="{% url 'music:deletealbum' album.id %}" method="post" style="display: inline;">
                    {% csrf_token %}

                    <button type="submit" class="btn btn-default btn-sm-2">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
                </h3>
            </div>
        </a>
    </div>
    </div>
{% endfor %}
</div>
</div>
{% endblock %}

music/templates/music/login.html
{% extends 'music/baselogin.html' %}
{% block title %} LOGIN {% endblock %}
{% block body %}

<div class="container">
	<div class="jumbotron">
		<h2 align="center" >WELCOME TO THE LOGIN PAGE</h2>
    </div>
</div>
<div class="container-fluid">
<div class="row">
    <div class="col-sm-5">
	    <div class="panel panel-default">
            <div class="panel-body">
                <form class="form-horizontal" role="form" action="{% url 'music:login_user' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="id_username">
                            USERNAME :
                        </label>
                        <div class="col-sm-6">
                            <input type="text" maxlength="30" name="username" id="id_username">
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="control-label col-sm-3" for="id_password">
                            PASSWORD :
                        </label>
                       <div class="col-sm-6">
                           <input type="password" id="id_password" name="password">
                       </div>
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-10">
                                <br><button type="submit" class="btn btn-success">Login</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="panel-footer">
                <h4>Dont have an account ? Click <a href="{% url 'music:register' %}">here</a> to register<h3>
            </div>'
        </div>
    </div>
    <div class="col-sm-offset-9">
      <h3>Whats in there for you ?</h3><br><br>
      <h4>You can manage your albums and songs<br>
          You can also edit and update your albums details
          {{error_message}}
      </h4>
        <small><marquee><span class="badge">-developed by Mayank</span></marquee></small>
	</div>
</div>
</div>
{% endblock %}

music/templates/music/profile.html
{% extends 'music/base.html' %}
{% block profile %}Active{% endblock %}
{% block body %}
<br><br><br><br>
<div class="col-sm-6">
    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table">
                <thead>
                    <tr>
                        <th><b>USERNAME</b></th>
                        <th><b>EMAIL</b></th>
                    </tr>
                </thead>
                <tbody>
                <tr>
                    <td><i>{{request.user.username}}</i></td>
                    <td><i>{{request.user.email}}</i></td>
                </tr>
{% endblock %}

music/templates/music/registration_form.html
{% extends 'music/baselogin.html' %}
{% block title %}Create New Account{% endblock %}
{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" role="post" action="{% url 'music:register' %}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'music/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-md-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

music/templates/music/test_angular.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>angular</title>
    <script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.6.4/angular.min.js"></script>
</head>
<body>
<div ng-app="myapp" ng-controller="myctrl" ng-init="'textarea':'MAYANK">
    <p ng-bind="textarea">
</div>

<script>
    var url_website = "http://127.0.0.1:8000/music/getjson";
    var app = angular.module('myapp',[]);
    app.controller('myctrl', function ($scope, $http) {
        setInterval(function() {
            $http.get(url_website).then(function (response) {
                $scope.myData = response.data;
                angular.forEach($scope.myData, function (object) {
                    $scope.textarea += object.fields['album_title'] + "\n";
                });

            }, function () {
                alert('there was some error');
            });
        },10000);
    });
</script>
</body>
</html>